<?php

/**
 * Implements hook_views_api().
 */
function roparun_team_portal_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'roparun_team_portal'),
  );
}

/**
 * Implements hook_views_default_views().
 */
function roparun_team_portal_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module', 'roparun_team_portal'). '/views', '/.inc/');
  $views = array();
  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}

/**
 * Implements hook_permission().
 */
function roparun_team_portal_permission() {
  return array(
    'access team id profile field' => array(
      'title' => t('Access to the Team ID profile field'),
    )
  );
}


function roparun_team_portal_civimrf_user_update_alter(&$edit, $contact) {
	if (isset($contact['team_id'])) {
		$edit['roparun_team_portal_team_id']['und'][0]['value'] = $contact['team_id'];
	}
}

function roparun_team_portal_civimrf_user_new_alter(&$edit, $contact) {
	if (isset($contact['team_id'])) {
		$edit['roparun_team_portal_team_id']['und'][0]['value'] = $contact['team_id'];
	}
}

/**
 * Hide the uid field from the form.
 */
function roparun_team_portal_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  if (!user_access('access team id profile field')) {
    $form['roparun_team_portal_team_id']['#access'] = false;
  }
}

/**
 * Hide the uid field from the user profile
 */
function roparun_team_portal_preprocess_user_profile(&$vars) {
  if (!user_access('access team id profile field')) {
		unset($vars['user_profile']['roparun_team_portal_team_id']);
	}
}
